/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsStudentManagementSystemImport } from './routes/projects/student-management-system'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsStudentManagementSystemRoute =
  ProjectsStudentManagementSystemImport.update({
    id: '/projects/student-management-system',
    path: '/projects/student-management-system',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/student-management-system': {
      id: '/projects/student-management-system'
      path: '/projects/student-management-system'
      fullPath: '/projects/student-management-system'
      preLoaderRoute: typeof ProjectsStudentManagementSystemImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/student-management-system': typeof ProjectsStudentManagementSystemRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/student-management-system': typeof ProjectsStudentManagementSystemRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/projects/student-management-system': typeof ProjectsStudentManagementSystemRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/student-management-system'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/student-management-system'
  id: '__root__' | '/' | '/projects/student-management-system'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsStudentManagementSystemRoute: typeof ProjectsStudentManagementSystemRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsStudentManagementSystemRoute: ProjectsStudentManagementSystemRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/projects/student-management-system"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/projects/student-management-system": {
      "filePath": "projects/student-management-system.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
